baseURL = "https://hugotion.github.io/j5724cypragmk3gnpcmvjd1w5x7hzyte/"
defaultLanguage = "en"
title = "MDFriday"
description = "MDFriday homepage, showcase the product or service."
theme = "theme-long-teng"

[params]
    Author = 'sunwei'